name: Checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**/*.md"
      - "**/*.png"
      - "**/*.json"

jobs:
  test:
    permissions:
      pull-requests: write
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.12]
        poetry-version: [1.4.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: make init
      - name: Run tests
        run: make tests
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          badge-title: coverage
          create-new-comment: true
  code-quality:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        poetry-version: [1.4.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: make init
      - name: Run style checks
        run: make check-formatting
